apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-autoscaler-status-exporter.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-autoscaler-status-exporter.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-autoscaler-status-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}